#!/bin/bash

TICKETS_PATH="$( dirname $BASH_SOURCE )"
TICKETS_PATH="$TICKETS_PATH/tickets"
TICKETS_PATH="$( realpath $TICKETS_PATH )"

cd $TICKETS_PATH
COUNT=0

for i in *.ticket
do
  grep "Status: Open" "$i" > /dev/null
  if test 0 -eq $?
  then
    COUNT=$((COUNT + 1))
    echo -n "$i:"
    grep Summary "$i"
  fi 
done

echo
echo "There are $COUNT open tickets in total."
