#!/bin/bash

TICKETS_PATH="$( dirname $BASH_SOURCE )"
TICKETS_PATH="$TICKETS_PATH/tickets"
TICKETS_PATH="$( realpath $TICKETS_PATH )"

cd $TICKETS_PATH

for TICKET in $(grep --color=never -l "Status: Closed" *.ticket)
do
    echo -n "$TICKET "
    grep --color=always "Resolution:" "$TICKET"        \
        | sed "s/Completed/\\x1b[92mCompleted\\x1b[39m/" \
        | sed "s/Delegated/\\x1b[94mDelegated\\x1b[39m/" \
        | sed "s/Postponed/\\x1b[93mPostponed\\x1b[39m/" \
        | sed "s/Cancelled/\\x1b[91mCancelled\\x1b[39m/" \
        | sed "s/Invalid/\\x1b[95mInvalid\\x1b[39m/"

done
