#!/bin/bash

MILESTONES_PATH="$( dirname $BASH_SOURCE )"
MILESTONES_PATH="$MILESTONES_PATH/milestones"
MILESTONES_PATH="$( realpath $MILESTONES_PATH )"

cd $MILESTONES_PATH

for i in *.milestone
do
  # Skip template
    if test "$i" = "000.milestone"
    then continue
    fi

  # Detect open and closed tickets
    OPEN_LINE=$(grep --color=never -n "=== Open Tickets ===" "$i" | grep --color=never -o -E "^.*:")
    OPEN_LINE="${OPEN_LINE%:}"   # remove ":" character from grep result

    CLOSE_LINE=$(grep --color=never -n "=== Closed Tickets ===" "$i" | grep --color=never -o -E "^.*:")
    CLOSE_LINE="${CLOSE_LINE%:}"   # remove ":" character from grep result

    NUM_OPEN_TICKETS=$( cat "$i" | head -n "+$(( CLOSE_LINE - 1 ))" | tail -n "+$(( OPEN_LINE + 1 ))" | wc -w )

    if   test "$NUM_OPEN_TICKETS" -gt 0
    then continue
    fi

    NUM_CLOSED_TICKETS=$( cat "$i" | tail -n "+$(( CLOSE_LINE + 1 ))" | wc -w )

  # Print entry to terminal (unsorted)
    printf "%-15s -- " "Milestone ${i%.milestone}"
    printf "%-27s -- " "Completion: ${NUM_CLOSED_TICKETS} / $(( NUM_OPEN_TICKETS + NUM_CLOSED_TICKETS )) ($((100 * NUM_CLOSED_TICKETS / (NUM_OPEN_TICKETS + NUM_CLOSED_TICKETS)))%)"
    grep --color=never "      Title:" "$i" | cut -d$':' -f2
done
