#!/bin/bash

# In order for a directory to be a valid 'bashtickets repository', it needs to
 # contain a directory called '.bashtickets'; this directory should contain a
  # file called "config", which should be sourceable without errors.
  # Furthermore, it should contain a directory called 'tickets', and a directory
  # called 'milestones'.

# Note: the 'error' function used here is defined in the main bashtickets script
 # and exported here

  if   test -d ./.bashtickets
  then :
  else error "Error: Not a valid bashtickets repository ('.bashtickets' directory missing)"
       exit -1
  fi

  if   test -f ./.bashtickets/config
  then :
  else error "Error: Not a valid bashtickets repository ('.bashtickets/config' file missing)"
       exit -1
  fi

  # test if the config file can be sourced without errors
  ( set -e; source ./.bashtickets/config )
  if   test $? -eq 0
  then :
  else error "Error: Not a valid bashtickets repository (errors found in '.bashtickets/config' file)"
       exit -1
  fi

  if   test -d ./tickets
  then :
  else error "Error: Not a valid bashtickets repository ('tickets' directory missing)"
       exit -1
  fi

  if   test -d ./milestones
  then :
  else error "Error: Not a valid bashtickets repository ('milestones' directory missing)"
       exit -1
  fi

  exit 0
