#!/bin/bash

case "$1" in
    ("ticket")     shift && "$BT_UTILS_DIR/new_ticket"    "$@" ;;
    ("milestone")  shift && "$BT_UTILS_DIR/new_milestone" "$@" ;;
    (*)            error "Error: invalid argument given to 'new'."
                   error "Valid arguments are 'ticket' or 'milestone'."
                   exit 1 ;;
esac
