#!/bin/bash

## Note: the 'error' function used here is defined in the main bashtickets
  # script and exported here

case "$1" in
    ("ticket")     shift && "$BT_UTILS_DIR/new_ticket"    "$@" ;;
    ("milestone")  shift && "$BT_UTILS_DIR/new_milestone" "$@" ;;
    (*)            error "Error: invalid argument given to 'new'."
                   error "Valid arguments are 'ticket' or 'milestone'."
                   exit 1 ;;
esac
