#!/bin/bash

TICKETS_PATH="$( dirname $BASH_SOURCE )"
TICKETS_PATH="$TICKETS_PATH/tickets"
TICKETS_PATH="$( realpath $TICKETS_PATH )"

ANSI_COLOR_LIGHTBLUE="\033[94m"
ANSI_BOLD_ON="\033[1m"
ANSI_BOLD_OFF="\033[22m"
ANSI_COLOR_OFF="\033[39m"

cd $TICKETS_PATH

OWNERS="$(grep --color=never 'Owner:' *.ticket | cut -b 18- | sort -u)"

while read OWNER
do
  OWNERS_NAME=${OWNER:6}
  OWNERS_TICKETS="$( grep -l -E "Owner:${OWNERS_NAME}$" *.ticket )"

  COUNT=0
  PRINTOUT=

  for i in $OWNERS_TICKETS;
  do
    grep "Status: Open" "$i" > /dev/null

    if test 0 -eq $?
    then
      COUNT=$((COUNT + 1))
      PRINTOUT="$PRINTOUT$i:"
      PRINTOUT="$PRINTOUT $(grep Summary "$i")"
      PRINTOUT=${PRINTOUT}$'\n'
    fi

  done

  echo -e "${ANSI_COLOR_LIGHTBLUE}== ${ANSI_BOLD_ON}Owner:${OWNERS_NAME:- (Nobody)}${ANSI_BOLD_OFF} (${COUNT} open tickets)${ANSI_COLOR_OFF}"
  echo "$PRINTOUT"

done <<< "$OWNERS"

