#!/bin/bash

MILESTONES_PATH="$( dirname $BASH_SOURCE )"
MILESTONES_PATH="$MILESTONES_PATH/milestones"
MILESTONES_PATH="$( realpath $MILESTONES_PATH )"

cd $MILESTONES_PATH

for i in *.milestone
do
  # Skip template
    if test "$i" = "000.milestone"
    then continue
    fi

  # Detect open and closed tickets
    OPEN_LINE=$(grep --color=never -n "=== Open Tickets ===" "$i" | grep --color=never -o -E "^.*:")
    OPEN_LINE="${OPEN_LINE%:}"   # remove ":" character from grep result

    CLOSE_LINE=$(grep --color=never -n "=== Closed Tickets ===" "$i" | grep --color=never -o -E "^.*:")
    CLOSE_LINE="${CLOSE_LINE%:}"   # remove ":" character from grep result

    NUM_OPEN_TICKETS=$( cat "$i" | head -n "+$(( CLOSE_LINE - 1 ))" | tail -n "+$(( OPEN_LINE + 1 ))" |  egrep "^\s*\$" -v | wc -l )

    if   test "$NUM_OPEN_TICKETS" -eq 0
    then continue
    fi

    NUM_CLOSED_TICKETS=$( cat "$i" | tail -n "+$(( CLOSE_LINE + 1 ))" |  egrep "^\s*\$" -v | wc -l )

  # Calculate days left from deadline (assumes correct date format!)
    DEADLINE=$(grep --color=never "   Deadline: " "$i" | cut -d$':' -f2 )
    DEADLINE=$(date --date "$DEADLINE" "+%s")
    TODAY=$(date "+%s")
    DAYS_LEFT=$(( (DEADLINE - TODAY) / 86400 ))

  # Print entry to terminal (unsorted)
    printf "%-15s -- " "Milestone ${i%.milestone}"
    printf "%-27s -- " "Completion: ${NUM_CLOSED_TICKETS} / $(( NUM_OPEN_TICKETS + NUM_CLOSED_TICKETS )) ($((100 * NUM_CLOSED_TICKETS / (NUM_OPEN_TICKETS + NUM_CLOSED_TICKETS)))%)"
    printf "%-15s -- " "Days left: ${DAYS_LEFT}"
    printf "Title: " && grep --color=never "      Title:" "$i" | cut -d$':' -f2
done
